import = [
    "~/.config/alacritty/themes/enfocado_dark.toml"
]

[window]
dimensions = { columns = 150, lines = 35 }
opacity=0.8

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On"}
thickness = 0.2

