import = [
    "~/.config/alacritty/themes/campbell.toml"
]

[window]
padding = {x = 11, y = 8}

dimensions = { columns = 150, lines = 35 }
opacity=0.9

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On"}
thickness = 0.2

